DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    byUser INTEGER
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY(byUser) REFERENCES user(id)
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT ,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  age INTEGER,
  country TEXT
);