@startuml sekvens
actor User
User -> Payment: Rent guide

activate Payment
User -> Payment: Paymentinformation
Payment -> CardPayment: Payment

activate CardPayment
CardPayment -> CardTerminal: Validate payment

alt #LightGreen Success
    activate CardTerminal
    |||
    CardTerminal --> CardPayment: Payment sucessfull
    CardPayment --> Payment: Payment sucessfull

    database Database
    Payment -> User: Sucessfull booking
    Payment -> Database: Update database
    deactivate Payment

else #Pink Failure
    CardTerminal --> CardPayment: Payment denied
    deactivate CardTerminal

    CardPayment --> Payment: Payment denied
    deactivate CardPayment

    Payment --> User: Unsucessfull booking
end
|||
@endumll